# Generated by Django 4.2.5 on 2023-09-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphones', '0003_alter_smartphone_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='time_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
